trigger: none

variables:
    vmImageName: 'terraform'
    azureServiceConnection: 'My-Subscription-service-connection'
    resourceGroupName: 'My-devops-bicep-dev'
    location: 'West US'
    templateFile: 'appService/default/main.bicep'
    parameterfile: 'appService/dev/parameters.json'
    devtemplateFile: 'appService/dev/main.bicep'
    devparameterfile: 'appService/dev/parameters.json'
stages:
    - stage: dev
      jobs:
      - deployment: deploydev
        continueOnError: false
        environment: 'dev'
        pool: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'My-Subscription-service-connection'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                        az --version
                        az group create --name $(resourceGroupName) --location $(location)
                        az deployment group create --resource-group $(resourceGroupName) --template-file 'appService/default/main.bicep' --parameters $(parameterfile)
    - stage: dev
      jobs:
      - deployment: deployDev
        continueOnError: false
        environment: 'dev'
        pool: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'My-Subscription-service-connection'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                        az --version
                        az group create --name $(resourceGroupName) --location $(location)
                        az deployment group create --resource-group $(resourceGroupName) --template-file $(devtemplateFile) --parameters $(parameterfile)